---
title: "Lab 07 - University of Edinburgh Art Collection"
author: "Marcus Minko"
date: "02-26-2022"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(skimr)
```

```{r load-data, message = FALSE}
# Remove eval = FALSE or set it to TRUE once data is ready to be loaded
uoe_art <- read_csv("data/uoe-art.csv")
```

### Exercise 9

```{r separate-title-date, error = TRUE}
uoe_art <- uoe_art %>%
  separate(title, into = c("title", "date"), sep = "\\(") %>%
  mutate(year = str_remove(date, "\\)") %>% as.numeric()) %>%
  select(title, artist, year, link)
```

### Exercise 10

```{r skim}

skim(uoe_art)

#1,369 have the year missing

uoe_art %>%
  na.omit() %>% 
  ggplot(aes(x = year)) + 
  geom_histogram(binwidth = 10) + 
  xlim(1818, 2020) +
  theme_linedraw() +
  labs(
        title = "Number of Artworks by Year", 
        subtitle = "University of Edinburgh",
        x = "Year", 
        y = "# of Artworks")

#replace the erroneous year 2 with correct 1964

uoe_art <- uoe_art %>% 
  mutate(
        year = replace(year, 
                       year == 2, 1964))

#Which artist has the most art pieces in this collection

uoe_art %>% 
      count(artist, sort = TRUE)

#Emma Gillies; my guess is that this artist is local to Edinburgh

#How many titles contain the word "Child" or "child"

uoe_art %>% 
    filter(
          str_detect(
            title, "Child | child")
           )
# 4
```

